#!/usr/bin/env python3
"""
Standalone Fine-tuning Script for fastino/gliner2-privacy-filter-PII-multi on Taiwan PII.
Generated by PII-Synthea FineTuneRecipe Engine.

Prerequisites:
    uv add torch torchvision --index-url https://download.pytorch.org/whl/cu126
    uv add "gliner2[train]>=0.2.0" peft
"""

import argparse
import logging
import sys
from pathlib import Path

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("train_gliner2_tw")


def parse_args():
    parser = argparse.ArgumentParser(
        description="PII-Synthea: GLiNER2 Taiwan PII Fine-tuning Suite"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run a fast dry-run with 100 train samples and 1 epoch to verify VRAM and pipeline.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=None,
        help="Limit number of training samples (defaults to 100 if --dry-run is set).",
    )
    parser.add_argument(
        "--train-data",
        type=str,
        default="data/gliner2_tw/train.jsonl",
        help="Path to training dataset JSONL (default: data/gliner2_tw/train.jsonl).",
    )
    parser.add_argument(
        "--val-data",
        type=str,
        default="data/gliner2_tw/val.jsonl",
        help="Path to validation dataset JSONL (default: data/gliner2_tw/val.jsonl).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="Per-device batch size (default: 4).",
    )
    parser.add_argument(
        "--gradient-accumulation-steps",
        type=int,
        default=4,
        help="Gradient accumulation steps (default: 4, effective batch size = batch_size * steps).",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=None,
        help="Number of training epochs (default: 1 for dry-run, 10 for full training).",
    )
    parser.add_argument(
        "--fp16",
        action="store_true",
        default=True,
        help="Enable FP16 mixed precision training (default: True).",
    )
    parser.add_argument(
        "--no-fp16",
        action="store_false",
        dest="fp16",
        help="Disable FP16 mixed precision training.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=0,
        help="Dataloader num_workers (default: 0 for Windows safety).",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for model weights/checkpoints.",
    )
    parser.add_argument(
        "--max-len",
        type=int,
        default=None,
        metavar="N",
        help="Cap tokenized sequence length (truncates long samples). Recommended 512 on 8GB GPUs.",
    )
    parser.add_argument(
        "--eval-batch-size",
        type=int,
        default=None,
        help="Evaluation batch size (default: same as --batch-size).",
    )
    parser.add_argument(
        "--gradient-checkpointing",
        action="store_true",
        help="Trade compute for lower VRAM (encoder activation checkpointing).",
    )
    parser.add_argument(
        "--low-vram",
        action="store_true",
        help="Preset for ~8GB GPUs: max_len=512, batch_size=1, grad_accum=1, gradient checkpointing.",
    )
    return parser.parse_args()


def apply_cli_presets(args: argparse.Namespace) -> None:
    if args.low_vram:
        if args.max_len is None:
            args.max_len = 512
        args.batch_size = 1
        args.gradient_accumulation_steps = 1
        args.gradient_checkpointing = True
    if args.eval_batch_size is None:
        args.eval_batch_size = args.batch_size


def count_jsonl_lines(path: Path) -> int:
    if not path.is_file():
        return 0
    with open(path, "r", encoding="utf-8") as f:
        return sum(1 for line in f if line.strip())


def prepare_sample_dataset(source_path: Path, max_samples: int, prefix: str = "train") -> Path:
    """Creates a temporary sliced dataset file for dry-run testing."""
    target_path = source_path.parent / f"{prefix}_dryrun_{max_samples}.jsonl"
    logger.info(f"Preparing {prefix} subset of {max_samples} samples -> {target_path}...")
    count = 0
    with open(source_path, "r", encoding="utf-8") as f_in, open(target_path, "w", encoding="utf-8") as f_out:
        for line in f_in:
            if count >= max_samples:
                break
            line_str = line.strip()
            if line_str:
                f_out.write(line_str + "\n")
                count += 1
    logger.info(f"Wrote {count} samples to {target_path}")
    return target_path


def main():
    args = parse_args()
    apply_cli_presets(args)

    try:
        import torch
        from gliner2 import AutoExtractor
        from gliner2.processor import CharLevelSplitter
        from gliner2.training.data import TrainingDataset
        from gliner2.training.trainer import ExtractorTrainer, TrainingConfig
    except ImportError as e:
        logger.error(
            f"Missing required packages ({e}). Please ensure torch and gliner2[train] are installed."
        )
        sys.exit(1)

    # 1. Paths & Verification
    train_path = Path(args.train_data)
    val_path = Path(args.val_data)
    
    if args.output_dir:
        output_dir = Path(args.output_dir)
    elif args.dry_run:
        output_dir = Path("./models/gliner2_tw_pii_dryrun")
    else:
        output_dir = Path("./models/gliner2_tw_pii")

    if not train_path.exists():
        logger.error(f"Training dataset not found at {train_path.resolve()}")
        logger.error("Please run: python main.py generate-dataset --count 5000")
        sys.exit(1)

    # Determine max train samples and epochs
    max_train_samples = args.max_samples
    if args.dry_run and max_train_samples is None:
        max_train_samples = 100

    num_epochs = args.epochs
    if num_epochs is None:
        num_epochs = 1 if args.dry_run else 10

    logging_steps = 1 if args.dry_run else 10

    # Log GPU / CUDA Environment
    logger.info("=" * 70)
    logger.info("PII-Synthea: GLiNER2 Taiwan PII Fine-tuning Suite")
    logger.info(f"Dry-run mode : {args.dry_run} (samples: {max_train_samples or 'full'}, epochs: {num_epochs})")
    logger.info(f"CUDA available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        total_vram_mb = torch.cuda.get_device_properties(0).total_memory / (1024 ** 2)
        allocated_mb = torch.cuda.memory_allocated(0) / (1024 ** 2)
        reserved_mb = torch.cuda.memory_reserved(0) / (1024 ** 2)
        logger.info(f"GPU device   : {gpu_name} (Total VRAM: {total_vram_mb:.0f} MB)")
        logger.info(f"Current VRAM : {allocated_mb:.1f} MB allocated, {reserved_mb:.1f} MB reserved")
        torch.cuda.reset_peak_memory_stats(0)

    logger.info(f"Base model    : fastino/gliner2-privacy-filter-PII-multi")
    logger.info(f"Batch size    : {args.batch_size} (acc steps: {args.gradient_accumulation_steps}, effective: {args.batch_size * args.gradient_accumulation_steps})")
    logger.info(f"Eval batch    : {args.eval_batch_size}")
    logger.info(f"Max seq len   : {args.max_len if args.max_len is not None else 'none (full length)'}")
    logger.info(f"Grad checkpoint: {args.gradient_checkpointing}")
    logger.info(f"Low-VRAM preset: {args.low_vram}")
    logger.info(f"FP16 enabled  : {args.fp16}")
    logger.info(f"Output dir    : {output_dir.resolve()}")
    logger.info("=" * 70)

    # 2. Load Base Model & Inject Chinese Word Splitter
    logger.info("Loading pretrained GLiNER2 model...")
    model = AutoExtractor.from_pretrained("fastino/gliner2-privacy-filter-PII-multi")

    # CRITICAL: For Traditional Chinese, set CharLevelSplitter so Chinese characters
    # are tokenized by character while keeping Latin words/emails intact.
    logger.info("Configuring CharLevelSplitter for Chinese language support...")
    model.set_word_splitter(CharLevelSplitter())

    # 3. Load Datasets (apply subsetting if requested)
    active_train_path = train_path
    active_val_path = val_path if val_path.exists() else None

    if max_train_samples is not None:
        active_train_path = prepare_sample_dataset(train_path, max_train_samples, prefix="train")
        if val_path.exists():
            val_samples = min(max(max_train_samples // 5, 10), 50)
            active_val_path = prepare_sample_dataset(val_path, val_samples, prefix="val")

    logger.info(f"Loading training data from {active_train_path}...")
    train_dataset = TrainingDataset.load(str(active_train_path))
    logger.info("Validating dataset integrity...")
    try:
        train_dataset.validate(raise_on_error=False)
        train_dataset.print_stats()
    except Exception as e:
        logger.warning(f"Dataset validation note: {e}")

    val_dataset = None
    if active_val_path and active_val_path.exists():
        logger.info(f"Loading validation data from {active_val_path}...")
        val_dataset = TrainingDataset.load(str(active_val_path))

    # 4. Configure Training Parameters
    logger.info("Initializing TrainingConfig...")
    config_dict = {
        "output_dir": str(output_dir),
        "experiment_name": "gliner2_tw_pii_dryrun" if args.dry_run else "gliner2_tw_pii_finetune",
        "num_epochs": num_epochs,
        "max_steps": -1,
        "batch_size": args.batch_size,
        "eval_batch_size": args.eval_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "max_len": args.max_len,
        "gradient_checkpointing": args.gradient_checkpointing,
        "encoder_lr": 1e-05,
        "task_lr": 0.0005,
        "weight_decay": 0.01,
        "max_grad_norm": 1.0,
        "scheduler_type": "cosine",
        "warmup_ratio": 0.1,
        "warmup_steps": 0,
        "fp16": args.fp16,
        "bf16": False,
        "eval_strategy": "epoch",
        "eval_steps": 250,
        "save_best": True,
        "metric_for_best": "eval_loss",
        "greater_is_better": False,
        "save_total_limit": 2,
        "early_stopping": not args.dry_run,
        "early_stopping_patience": 3,
        "early_stopping_threshold": 0.001,
        "num_workers": args.num_workers,
        "pin_memory": True,
        "seed": 42,
        "group_by_length": True,
        "use_lora": True,
        "lora_r": 16,
        "lora_alpha": 32.0,
        "lora_dropout": 0.05,
        "lora_target_modules": [
            "encoder",
            "span_rep",
            "classifier",
            "count_embed",
            "count_pred",
        ],
        "save_adapter_only": True,
        "logging_steps": logging_steps,
        "report_to_wandb": False,
        "wandb_project": "gliner2-tw-pii",
    }

    # Instantiate TrainingConfig
    trainer_config = TrainingConfig(**config_dict)

    # 5. Initialize Trainer and Execute Training
    logger.info("Initializing ExtractorTrainer...")
    trainer = ExtractorTrainer(model=model, config=trainer_config)

    failed_batches_path = output_dir / "failed_batches.jsonl"
    output_dir.mkdir(parents=True, exist_ok=True)
    oom_events_before = count_jsonl_lines(failed_batches_path)

    logger.info("Starting fine-tuning...")
    results = trainer.train(
        train_data=train_dataset,
        eval_data=val_dataset,
    )

    logger.info("=" * 70)
    logger.info("Training completed successfully!")
    if isinstance(results, dict):
        for k, v in results.items():
            logger.info(f"  {k}: {v}")
    logger.info(f"Saved fine-tuned artifacts to: {output_dir.resolve()}")

    oom_events_this_run = count_jsonl_lines(failed_batches_path) - oom_events_before
    if torch.cuda.is_available():
        peak_allocated_mb = torch.cuda.max_memory_allocated(0) / (1024 ** 2)
        peak_reserved_mb = torch.cuda.max_memory_reserved(0) / (1024 ** 2)
        logger.info(f"Peak VRAM Allocated : {peak_allocated_mb:.1f} MB")
        logger.info(f"Peak VRAM Reserved  : {peak_reserved_mb:.1f} MB")
    logger.info(f"OOM skipped batches : {oom_events_this_run} (see {failed_batches_path.resolve()})")
    if oom_events_this_run == 0:
        gpu_label = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"
        logger.info(f"VRAM Safety Check   : OK (no OOM-skipped batches on {gpu_label})")
    else:
        logger.warning(
            "VRAM Safety Check   : DEGRADED — reduce --max-len, enable --gradient-checkpointing, "
            "or use --low-vram"
        )
    logger.info("=" * 70)

    # 6. Verification Inference Test
    logger.info("Running post-training inference verification on sample Taiwan PII...")
    test_text = (
        "立約人陳大明（身分證字號：A123456789，電話：0912-345-678）"
        "與台灣積體電路（統編：22099131，地址：新竹市東區研新一路9號）簽署契約。"
    )
    labels = ["person", "national_id_number", "phone_number", "tax_id", "address"]

    test_model = model
    test_model.set_word_splitter(CharLevelSplitter())
    preds = test_model.extract_entities(test_text, labels, threshold=0.5)

    logger.info(f"Input Text : {test_text}")
    logger.info(f"Predictions: {preds}")
    logger.info("Fine-tuning pipeline verification complete!")


if __name__ == "__main__":
    main()
