#!/usr/bin/env python3
"""
Standalone Fine-tuning Script for fastino/gliner2-privacy-filter-PII-multi on Taiwan PII.
Generated by PII-Synthea FineTuneRecipe Engine.

Prerequisites:
    pip install "gliner2[train]>=0.2.0" torch transformers peft
"""

import os
import sys
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("train_gliner2_tw")

def main():
    try:
        from gliner2 import AutoExtractor
        from gliner2.processor import CharLevelSplitter
        from gliner2.training.data import TrainingDataset
        from gliner2.training.trainer import ExtractorTrainer, TrainingConfig
    except ImportError as e:
        logger.error(
            "Missing required packages. Please install via: pip install \"gliner2[train]\" torch peft"
        )
        sys.exit(1)

    # 1. Paths & Verification
    train_path = Path("data/gliner2_tw/train.jsonl")
    val_path = Path("data/gliner2_tw/val.jsonl")
    output_dir = Path("./models/gliner2_tw_pii")

    if not train_path.exists():
        logger.error(f"Training dataset not found at {train_path.resolve()}")
        logger.error("Please run: python main.py generate-dataset --count 5000")
        sys.exit(1)

    logger.info("=" * 70)
    logger.info("PII-Synthea: GLiNER2 Taiwan PII Fine-tuning Suite")
    logger.info(f"Base model    : fastino/gliner2-privacy-filter-PII-multi")
    logger.info(f"Train dataset : {train_path.resolve()}")
    logger.info(f"Val dataset   : {val_path.resolve()} (exists: {val_path.exists()})")
    logger.info(f"Output dir    : {output_dir.resolve()}")
    logger.info(f"LoRA enabled  : True (r=16, alpha=32.0)")
    logger.info(f"Word Splitter : CharLevelSplitter (Chinese character boundary support)")
    logger.info("=" * 70)

    # 2. Load Base Model & Inject Chinese Word Splitter
    logger.info("Loading pretrained GLiNER2 model...")
    model = AutoExtractor.from_pretrained("fastino/gliner2-privacy-filter-PII-multi")

    # CRITICAL: For Traditional Chinese, set CharLevelSplitter so Chinese characters
    # are tokenized by character while keeping Latin words/emails intact.
    logger.info("Configuring CharLevelSplitter for Chinese language support...")
    model.set_word_splitter(CharLevelSplitter())

    # 3. Load and Validate Datasets
    logger.info(f"Loading training data from {train_path}...")
    train_dataset = TrainingDataset.load(str(train_path))
    logger.info("Validating dataset integrity...")
    try:
        train_dataset.validate(strict=False, raise_on_error=False)
        train_dataset.print_stats()
    except Exception as e:
        logger.warning(f"Dataset validation note: {e}")

    val_dataset = None
    if val_path.exists():
        logger.info(f"Loading validation data from {val_path}...")
        val_dataset = TrainingDataset.load(str(val_path))

    # 4. Configure Training Parameters
    logger.info("Initializing TrainingConfig...")
    config_dict = {
    "output_dir": "./models/gliner2_tw_pii",
    "experiment_name": "gliner2_tw_pii_finetune",
    "num_epochs": 10,
    "max_steps": -1,
    "batch_size": 8,
    "eval_batch_size": 8,
    "gradient_accumulation_steps": 2,
    "encoder_lr": 1e-05,
    "task_lr": 0.0005,
    "weight_decay": 0.01,
    "max_grad_norm": 1.0,
    "scheduler_type": "cosine",
    "warmup_ratio": 0.1,
    "warmup_steps": 0,
    "fp16": true,
    "bf16": false,
    "eval_strategy": "epoch",
    "eval_steps": 250,
    "save_best": true,
    "metric_for_best": "eval_loss",
    "greater_is_better": false,
    "save_total_limit": 3,
    "early_stopping": true,
    "early_stopping_patience": 3,
    "early_stopping_threshold": 0.001,
    "num_workers": 4,
    "pin_memory": true,
    "seed": 42,
    "group_by_length": true,
    "use_lora": true,
    "lora_r": 16,
    "lora_alpha": 32.0,
    "lora_dropout": 0.05,
    "lora_target_modules": [
        "encoder",
        "span_rep",
        "classifier",
        "count_embed",
        "count_pred"
    ],
    "save_adapter_only": true,
    "logging_steps": 10,
    "report_to_wandb": false,
    "wandb_project": "gliner2-tw-pii"
}
    
    # Instantiate TrainingConfig
    trainer_config = TrainingConfig(**config_dict)

    # 5. Initialize Trainer and Execute Training
    logger.info("Initializing ExtractorTrainer...")
    trainer = ExtractorTrainer(model=model, config=trainer_config)

    logger.info("Starting fine-tuning...")
    results = trainer.train(
        train_data=train_dataset,
        eval_data=val_dataset,
    )

    logger.info("=" * 70)
    logger.info("Training completed successfully!")
    if isinstance(results, dict):
        for k, v in results.items():
            logger.info(f"  {k}: {v}")
    logger.info(f"Saved fine-tuned artifacts to: {output_dir.resolve()}")
    logger.info("=" * 70)

    # 6. Verification Inference Test
    logger.info("Running post-training inference verification on sample Taiwan PII...")
    test_text = (
        "立約人陳大明（身分證字號：A123456789，電話：0912-345-678）"
        "與台灣積體電路（統編：22099131，地址：新竹市東區研新一路9號）簽署契約。"
    )
    labels = ["person", "national_id_number", "phone_number", "tax_id", "address"]
    
    # Reload or use current model
    test_model = model
    test_model.set_word_splitter(CharLevelSplitter())
    preds = test_model.extract_entities(test_text, labels=labels, threshold=0.5)
    
    logger.info(f"Input Text : {test_text}")
    logger.info(f"Predictions: {preds}")
    logger.info("Fine-tuning pipeline verification complete!")

if __name__ == "__main__":
    main()
